#############################################################################
# Makefile for building: acceptanceBenchLibrary
# Generated by qmake (3.1) (Qt 6.5.3)
# Project:  acceptanceBenchLibrary.pro
# Template: app
# Command: /home/jakob/qt-host/bin/qmake6 -o Makefile acceptanceBenchLibrary.pro -qtconf /home/jakob/qt-raspi/bin/target_qt.conf -spec devices/linux-rasp-pi4-aarch64 CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = aarch64-linux-gnu-gcc
CXX           = aarch64-linux-gnu-g++
DEFINES       = -DQT_TESTLIB_LIB -DQT_SERIALBUS_LIB -DQT_NETWORK_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/home/jakob/acceptanceBenchLibrary"' -DQT_QML_DEBUG
CFLAGS        = -pipe -march=armv8-a --sysroot=/home/jakob/rpi-sysroot -g -Wall -Wextra -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -pipe -march=armv8-a --sysroot=/home/jakob/rpi-sysroot -g -std=gnu++1z -Wall -Wextra -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I../build-testBenchLibrary-Qt_6_5_3_qt_raspi-Debug -I../qt-raspi/include -I../qt-raspi/include/QtTest -I../qt-raspi/include/QtSerialBus -I../qt-raspi/include/QtNetwork -I../qt-raspi/include/QtSerialPort -I../qt-raspi/include/QtCore -I. -I../qt-raspi/mkspecs/devices/linux-rasp-pi4-aarch64
QMAKE         = /home/jakob/qt-host/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/jakob/qt-host/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /home/jakob/qt-host/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = acceptanceBenchLibrary1.0.0
DISTDIR = /home/jakob/acceptanceBenchLibrary/.tmp/acceptanceBenchLibrary1.0.0
LINK          = aarch64-linux-gnu-g++
LFLAGS        = -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed --sysroot=/home/jakob/rpi-sysroot -Wl,-rpath,/usr/local/qt6/lib -Wl,-rpath-link,/home/jakob/rpi-sysroot/usr/lib/aarch64-linux-gnu -Wl,-rpath-link,/home/jakob/rpi-sysroot/lib/aarch64-linux-gnu
LIBS          = $(SUBLIBS) -L/home/jakob/acceptanceBenchLibrary/../build-testBenchLibrary-Qt_6_5_3_qt_raspi-Debug/ -ltestBenchLibrary /home/jakob/qt-raspi/lib/libQt6Test.so /home/jakob/qt-raspi/lib/libQt6SerialBus.so /home/jakob/qt-raspi/lib/libQt6Network.so /home/jakob/qt-raspi/lib/libQt6SerialPort.so /home/jakob/qt-raspi/lib/libQt6Core.so -lpthread   
AR            = aarch64-linux-gnu-ar cqs
RANLIB        = 
SED           = sed
STRIP         = aarch64-linux-gnu-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = tst_test.cpp 
OBJECTS       = tst_test.o
DIST          = ../qt-raspi/mkspecs/features/spec_pre.prf \
		../qt-raspi/mkspecs/common/unix.conf \
		../qt-raspi/mkspecs/common/linux.conf \
		../qt-raspi/mkspecs/common/sanitize.conf \
		../qt-raspi/mkspecs/common/gcc-base.conf \
		../qt-raspi/mkspecs/common/gcc-base-unix.conf \
		../qt-raspi/mkspecs/common/g++-base.conf \
		../qt-raspi/mkspecs/common/g++-unix.conf \
		../qt-raspi/mkspecs/qdevice.pri \
		../qt-raspi/mkspecs/features/device_config.prf \
		../qt-raspi/mkspecs/devices/common/linux_device_pre.conf \
		../qt-raspi/mkspecs/devices/common/linux_device_post.conf \
		../qt-raspi/mkspecs/qconfig.pri \
		../qt-raspi/mkspecs/modules/qt_lib_charts.pri \
		../qt-raspi/mkspecs/modules/qt_lib_charts_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_chartsqml.pri \
		../qt-raspi/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_concurrent.pri \
		../qt-raspi/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_core.pri \
		../qt-raspi/mkspecs/modules/qt_lib_core_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_dbus.pri \
		../qt-raspi/mkspecs/modules/qt_lib_dbus_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_example_icons_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_fb_support_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_gui.pri \
		../qt-raspi/mkspecs/modules/qt_lib_gui_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_input_support_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_kms_support_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labsanimation.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labssettings.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labssettings_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labssharedimage.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_network.pri \
		../qt-raspi/mkspecs/modules/qt_lib_network_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_opengl.pri \
		../qt-raspi/mkspecs/modules/qt_lib_opengl_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_openglwidgets.pri \
		../qt-raspi/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_printsupport.pri \
		../qt-raspi/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qml.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qml_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlcore.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmldom_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlintegration.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlmodels.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmltest.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmltest_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quick.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quick_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quicklayouts.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickwidgets.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_serialbus.pri \
		../qt-raspi/mkspecs/modules/qt_lib_serialbus_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_serialport.pri \
		../qt-raspi/mkspecs/modules/qt_lib_serialport_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_shadertools.pri \
		../qt-raspi/mkspecs/modules/qt_lib_shadertools_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_sql.pri \
		../qt-raspi/mkspecs/modules/qt_lib_sql_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_testlib.pri \
		../qt-raspi/mkspecs/modules/qt_lib_testlib_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_widgets.pri \
		../qt-raspi/mkspecs/modules/qt_lib_widgets_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_xml.pri \
		../qt-raspi/mkspecs/modules/qt_lib_xml_private.pri \
		../qt-raspi/mkspecs/features/qt_functions.prf \
		../qt-raspi/mkspecs/features/qt_config.prf \
		../qt-raspi/mkspecs/devices/linux-rasp-pi4-aarch64/qmake.conf \
		../qt-raspi/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../qt-raspi/mkspecs/features/exclusive_builds.prf \
		../qt-raspi/mkspecs/features/toolchain.prf \
		../qt-raspi/mkspecs/features/default_pre.prf \
		../qt-raspi/mkspecs/features/resolve_config.prf \
		../qt-raspi/mkspecs/features/default_post.prf \
		../qt-raspi/mkspecs/features/testcase.prf \
		../qt-raspi/mkspecs/features/warn_on.prf \
		../qt-raspi/mkspecs/features/qt.prf \
		../qt-raspi/mkspecs/features/resources_functions.prf \
		../qt-raspi/mkspecs/features/resources.prf \
		../qt-raspi/mkspecs/features/moc.prf \
		../qt-raspi/mkspecs/features/testlib_defines.prf \
		../qt-raspi/mkspecs/features/unix/thread.prf \
		../qt-raspi/mkspecs/features/qml_debug.prf \
		../qt-raspi/mkspecs/features/qmake_use.prf \
		../qt-raspi/mkspecs/features/file_copies.prf \
		../qt-raspi/mkspecs/features/testcase_targets.prf \
		../qt-raspi/mkspecs/features/exceptions.prf \
		../qt-raspi/mkspecs/features/yacc.prf \
		../qt-raspi/mkspecs/features/lex.prf \
		acceptanceBenchLibrary.pro  tst_test.cpp
QMAKE_TARGET  = acceptanceBenchLibrary
DESTDIR       = 
TARGET        = acceptanceBenchLibrary


first: all
####### Build rules

acceptanceBenchLibrary: /home/jakob/acceptanceBenchLibrary/../build-testBenchLibrary-Qt_6_5_3_qt_raspi-Debug/libtestBenchLibrary.a $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: acceptanceBenchLibrary.pro ../qt-raspi/mkspecs/devices/linux-rasp-pi4-aarch64/qmake.conf ../qt-raspi/mkspecs/features/spec_pre.prf \
		../qt-raspi/mkspecs/common/unix.conf \
		../qt-raspi/mkspecs/common/linux.conf \
		../qt-raspi/mkspecs/common/sanitize.conf \
		../qt-raspi/mkspecs/common/gcc-base.conf \
		../qt-raspi/mkspecs/common/gcc-base-unix.conf \
		../qt-raspi/mkspecs/common/g++-base.conf \
		../qt-raspi/mkspecs/common/g++-unix.conf \
		../qt-raspi/mkspecs/qdevice.pri \
		../qt-raspi/mkspecs/features/device_config.prf \
		../qt-raspi/mkspecs/devices/common/linux_device_pre.conf \
		../qt-raspi/mkspecs/devices/common/linux_device_post.conf \
		../qt-raspi/mkspecs/qconfig.pri \
		../qt-raspi/mkspecs/modules/qt_lib_charts.pri \
		../qt-raspi/mkspecs/modules/qt_lib_charts_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_chartsqml.pri \
		../qt-raspi/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_concurrent.pri \
		../qt-raspi/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_core.pri \
		../qt-raspi/mkspecs/modules/qt_lib_core_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_dbus.pri \
		../qt-raspi/mkspecs/modules/qt_lib_dbus_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_example_icons_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_fb_support_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_gui.pri \
		../qt-raspi/mkspecs/modules/qt_lib_gui_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_input_support_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_kms_support_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labsanimation.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labssettings.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labssettings_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labssharedimage.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../qt-raspi/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_network.pri \
		../qt-raspi/mkspecs/modules/qt_lib_network_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_opengl.pri \
		../qt-raspi/mkspecs/modules/qt_lib_opengl_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_openglwidgets.pri \
		../qt-raspi/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_printsupport.pri \
		../qt-raspi/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qml.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qml_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlcore.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmldom_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlintegration.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlmodels.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmltest.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmltest_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../qt-raspi/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quick.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quick_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quicklayouts.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickwidgets.pri \
		../qt-raspi/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_serialbus.pri \
		../qt-raspi/mkspecs/modules/qt_lib_serialbus_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_serialport.pri \
		../qt-raspi/mkspecs/modules/qt_lib_serialport_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_shadertools.pri \
		../qt-raspi/mkspecs/modules/qt_lib_shadertools_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_sql.pri \
		../qt-raspi/mkspecs/modules/qt_lib_sql_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_testlib.pri \
		../qt-raspi/mkspecs/modules/qt_lib_testlib_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_widgets.pri \
		../qt-raspi/mkspecs/modules/qt_lib_widgets_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../qt-raspi/mkspecs/modules/qt_lib_xml.pri \
		../qt-raspi/mkspecs/modules/qt_lib_xml_private.pri \
		../qt-raspi/mkspecs/features/qt_functions.prf \
		../qt-raspi/mkspecs/features/qt_config.prf \
		../qt-raspi/mkspecs/devices/linux-rasp-pi4-aarch64/qmake.conf \
		../qt-raspi/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../qt-raspi/mkspecs/features/exclusive_builds.prf \
		../qt-raspi/mkspecs/features/toolchain.prf \
		../qt-raspi/mkspecs/features/default_pre.prf \
		../qt-raspi/mkspecs/features/resolve_config.prf \
		../qt-raspi/mkspecs/features/default_post.prf \
		../qt-raspi/mkspecs/features/testcase.prf \
		../qt-raspi/mkspecs/features/warn_on.prf \
		../qt-raspi/mkspecs/features/qt.prf \
		../qt-raspi/mkspecs/features/resources_functions.prf \
		../qt-raspi/mkspecs/features/resources.prf \
		../qt-raspi/mkspecs/features/moc.prf \
		../qt-raspi/mkspecs/features/testlib_defines.prf \
		../qt-raspi/mkspecs/features/unix/thread.prf \
		../qt-raspi/mkspecs/features/qml_debug.prf \
		../qt-raspi/mkspecs/features/qmake_use.prf \
		../qt-raspi/mkspecs/features/file_copies.prf \
		../qt-raspi/mkspecs/features/testcase_targets.prf \
		../qt-raspi/mkspecs/features/exceptions.prf \
		../qt-raspi/mkspecs/features/yacc.prf \
		../qt-raspi/mkspecs/features/lex.prf \
		acceptanceBenchLibrary.pro \
		../qt-raspi/lib/libQt6Test.prl \
		../qt-raspi/lib/libQt6SerialBus.prl \
		../qt-raspi/lib/libQt6Network.prl \
		../qt-raspi/lib/libQt6SerialPort.prl \
		../qt-raspi/lib/libQt6Core.prl
	$(QMAKE) -o Makefile acceptanceBenchLibrary.pro -qtconf /home/jakob/qt-raspi/bin/target_qt.conf -spec devices/linux-rasp-pi4-aarch64 CONFIG+=debug CONFIG+=qml_debug
../qt-raspi/mkspecs/features/spec_pre.prf:
../qt-raspi/mkspecs/common/unix.conf:
../qt-raspi/mkspecs/common/linux.conf:
../qt-raspi/mkspecs/common/sanitize.conf:
../qt-raspi/mkspecs/common/gcc-base.conf:
../qt-raspi/mkspecs/common/gcc-base-unix.conf:
../qt-raspi/mkspecs/common/g++-base.conf:
../qt-raspi/mkspecs/common/g++-unix.conf:
../qt-raspi/mkspecs/qdevice.pri:
../qt-raspi/mkspecs/features/device_config.prf:
../qt-raspi/mkspecs/devices/common/linux_device_pre.conf:
../qt-raspi/mkspecs/devices/common/linux_device_post.conf:
../qt-raspi/mkspecs/qconfig.pri:
../qt-raspi/mkspecs/modules/qt_lib_charts.pri:
../qt-raspi/mkspecs/modules/qt_lib_charts_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_chartsqml.pri:
../qt-raspi/mkspecs/modules/qt_lib_chartsqml_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_concurrent.pri:
../qt-raspi/mkspecs/modules/qt_lib_concurrent_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_core.pri:
../qt-raspi/mkspecs/modules/qt_lib_core_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_dbus.pri:
../qt-raspi/mkspecs/modules/qt_lib_dbus_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_example_icons_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_fb_support_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_gui.pri:
../qt-raspi/mkspecs/modules/qt_lib_gui_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_input_support_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_kms_support_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_labsanimation.pri:
../qt-raspi/mkspecs/modules/qt_lib_labsanimation_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../qt-raspi/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../qt-raspi/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_labssettings.pri:
../qt-raspi/mkspecs/modules/qt_lib_labssettings_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_labssharedimage.pri:
../qt-raspi/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../qt-raspi/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_network.pri:
../qt-raspi/mkspecs/modules/qt_lib_network_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_opengl.pri:
../qt-raspi/mkspecs/modules/qt_lib_opengl_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_openglwidgets.pri:
../qt-raspi/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_printsupport.pri:
../qt-raspi/mkspecs/modules/qt_lib_printsupport_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_qml.pri:
../qt-raspi/mkspecs/modules/qt_lib_qml_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_qmlcore.pri:
../qt-raspi/mkspecs/modules/qt_lib_qmlcore_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_qmldebug_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_qmldom_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_qmlintegration.pri:
../qt-raspi/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../qt-raspi/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_qmlmodels.pri:
../qt-raspi/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_qmltest.pri:
../qt-raspi/mkspecs/modules/qt_lib_qmltest_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../qt-raspi/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../qt-raspi/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_quick.pri:
../qt-raspi/mkspecs/modules/qt_lib_quick_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_quickcontrols2.pri:
../qt-raspi/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../qt-raspi/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_quickdialogs2.pri:
../qt-raspi/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../qt-raspi/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../qt-raspi/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_quickeffects_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_quicklayouts.pri:
../qt-raspi/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_quickparticles_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_quickshapes_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_quicktemplates2.pri:
../qt-raspi/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_quickwidgets.pri:
../qt-raspi/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_serialbus.pri:
../qt-raspi/mkspecs/modules/qt_lib_serialbus_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_serialport.pri:
../qt-raspi/mkspecs/modules/qt_lib_serialport_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_shadertools.pri:
../qt-raspi/mkspecs/modules/qt_lib_shadertools_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_sql.pri:
../qt-raspi/mkspecs/modules/qt_lib_sql_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_testlib.pri:
../qt-raspi/mkspecs/modules/qt_lib_testlib_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_widgets.pri:
../qt-raspi/mkspecs/modules/qt_lib_widgets_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../qt-raspi/mkspecs/modules/qt_lib_xml.pri:
../qt-raspi/mkspecs/modules/qt_lib_xml_private.pri:
../qt-raspi/mkspecs/features/qt_functions.prf:
../qt-raspi/mkspecs/features/qt_config.prf:
../qt-raspi/mkspecs/devices/linux-rasp-pi4-aarch64/qmake.conf:
../qt-raspi/mkspecs/features/spec_post.prf:
.qmake.stash:
../qt-raspi/mkspecs/features/exclusive_builds.prf:
../qt-raspi/mkspecs/features/toolchain.prf:
../qt-raspi/mkspecs/features/default_pre.prf:
../qt-raspi/mkspecs/features/resolve_config.prf:
../qt-raspi/mkspecs/features/default_post.prf:
../qt-raspi/mkspecs/features/testcase.prf:
../qt-raspi/mkspecs/features/warn_on.prf:
../qt-raspi/mkspecs/features/qt.prf:
../qt-raspi/mkspecs/features/resources_functions.prf:
../qt-raspi/mkspecs/features/resources.prf:
../qt-raspi/mkspecs/features/moc.prf:
../qt-raspi/mkspecs/features/testlib_defines.prf:
../qt-raspi/mkspecs/features/unix/thread.prf:
../qt-raspi/mkspecs/features/qml_debug.prf:
../qt-raspi/mkspecs/features/qmake_use.prf:
../qt-raspi/mkspecs/features/file_copies.prf:
../qt-raspi/mkspecs/features/testcase_targets.prf:
../qt-raspi/mkspecs/features/exceptions.prf:
../qt-raspi/mkspecs/features/yacc.prf:
../qt-raspi/mkspecs/features/lex.prf:
acceptanceBenchLibrary.pro:
../qt-raspi/lib/libQt6Test.prl:
../qt-raspi/lib/libQt6SerialBus.prl:
../qt-raspi/lib/libQt6Network.prl:
../qt-raspi/lib/libQt6SerialPort.prl:
../qt-raspi/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile acceptanceBenchLibrary.pro -qtconf /home/jakob/qt-raspi/bin/target_qt.conf -spec devices/linux-rasp-pi4-aarch64 CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile acceptanceBenchLibrary

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../qt-raspi/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents tst_test.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) /home/jakob/acceptanceBenchLibrary/target_wrapper.sh .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first
	/home/jakob/acceptanceBenchLibrary/target_wrapper.sh $(TESTRUNNER) ./$(QMAKE_TARGET) $(TESTARGS)

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../qt-raspi/mkspecs/features/data/dummy.cpp
	aarch64-linux-gnu-g++ -pipe -pipe -march=armv8-a --sysroot=/home/jakob/rpi-sysroot -g -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h ../qt-raspi/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all: tst_test.moc
compiler_moc_source_clean:
	-$(DEL_FILE) tst_test.moc
tst_test.moc: tst_test.cpp \
		../qt-raspi/include/QtTest/QtTest \
		../qt-raspi/include/QtTest/QtTestDepends \
		../qt-raspi/include/QtCore/QtCore \
		../qt-raspi/include/QtCore/QtCoreDepends \
		../qt-raspi/include/QtCore/qglobal.h \
		../qt-raspi/include/QtCore/qtversionchecks.h \
		../qt-raspi/include/QtCore/qconfig.h \
		../qt-raspi/include/QtCore/qtcore-config.h \
		../qt-raspi/include/QtCore/qtconfigmacros.h \
		../qt-raspi/include/QtCore/qtcoreexports.h \
		../qt-raspi/include/QtCore/qtpreprocessorsupport.h \
		../qt-raspi/include/QtCore/qtnoop.h \
		../qt-raspi/include/QtCore/qsystemdetection.h \
		../qt-raspi/include/QtCore/qprocessordetection.h \
		../qt-raspi/include/QtCore/qcompilerdetection.h \
		../qt-raspi/include/QtCore/qassert.h \
		../qt-raspi/include/QtCore/qtypes.h \
		../qt-raspi/include/QtCore/qtclasshelpermacros.h \
		../qt-raspi/include/QtCore/qtversion.h \
		../qt-raspi/include/QtCore/qtypeinfo.h \
		../qt-raspi/include/QtCore/qcontainerfwd.h \
		../qt-raspi/include/QtCore/qsysinfo.h \
		../qt-raspi/include/QtCore/qlogging.h \
		../qt-raspi/include/QtCore/qflags.h \
		../qt-raspi/include/QtCore/qcompare_impl.h \
		../qt-raspi/include/QtCore/qatomic.h \
		../qt-raspi/include/QtCore/qbasicatomic.h \
		../qt-raspi/include/QtCore/qatomic_cxx11.h \
		../qt-raspi/include/QtCore/qgenericatomic.h \
		../qt-raspi/include/QtCore/qconstructormacros.h \
		../qt-raspi/include/QtCore/qdarwinhelpers.h \
		../qt-raspi/include/QtCore/qexceptionhandling.h \
		../qt-raspi/include/QtCore/qforeach.h \
		../qt-raspi/include/QtCore/qtdeprecationmarkers.h \
		../qt-raspi/include/QtCore/qttypetraits.h \
		../qt-raspi/include/QtCore/qfunctionpointer.h \
		../qt-raspi/include/QtCore/qglobalstatic.h \
		../qt-raspi/include/QtCore/qmalloc.h \
		../qt-raspi/include/QtCore/qminmax.h \
		../qt-raspi/include/QtCore/qnumeric.h \
		../qt-raspi/include/QtCore/qoverload.h \
		../qt-raspi/include/QtCore/qswap.h \
		../qt-raspi/include/QtCore/qtenvironmentvariables.h \
		../qt-raspi/include/QtCore/qtresource.h \
		../qt-raspi/include/QtCore/qttranslation.h \
		../qt-raspi/include/QtCore/qversiontagging.h \
		../qt-raspi/include/QtCore/q20algorithm.h \
		../qt-raspi/include/QtCore/q20functional.h \
		../qt-raspi/include/QtCore/q20iterator.h \
		../qt-raspi/include/QtCore/q20memory.h \
		../qt-raspi/include/QtCore/q23functional.h \
		../qt-raspi/include/QtCore/qabstractanimation.h \
		../qt-raspi/include/QtCore/qobject.h \
		../qt-raspi/include/QtCore/qobjectdefs.h \
		../qt-raspi/include/QtCore/qnamespace.h \
		../qt-raspi/include/QtCore/qtmetamacros.h \
		../qt-raspi/include/QtCore/qobjectdefs_impl.h \
		../qt-raspi/include/QtCore/qstring.h \
		../qt-raspi/include/QtCore/qchar.h \
		../qt-raspi/include/QtCore/qstringview.h \
		../qt-raspi/include/QtCore/qbytearray.h \
		../qt-raspi/include/QtCore/qrefcount.h \
		../qt-raspi/include/QtCore/qarraydata.h \
		../qt-raspi/include/QtCore/qpair.h \
		../qt-raspi/include/QtCore/qarraydatapointer.h \
		../qt-raspi/include/QtCore/qarraydataops.h \
		../qt-raspi/include/QtCore/qcontainertools_impl.h \
		../qt-raspi/include/QtCore/qxptype_traits.h \
		../qt-raspi/include/QtCore/qbytearrayalgorithms.h \
		../qt-raspi/include/QtCore/qbytearrayview.h \
		../qt-raspi/include/QtCore/qstringfwd.h \
		../qt-raspi/include/QtCore/q20type_traits.h \
		../qt-raspi/include/QtCore/qstringliteral.h \
		../qt-raspi/include/QtCore/qstringalgorithms.h \
		../qt-raspi/include/QtCore/qanystringview.h \
		../qt-raspi/include/QtCore/qutf8stringview.h \
		../qt-raspi/include/QtCore/qstringtokenizer.h \
		../qt-raspi/include/QtCore/qstringbuilder.h \
		../qt-raspi/include/QtCore/qlist.h \
		../qt-raspi/include/QtCore/qhashfunctions.h \
		../qt-raspi/include/QtCore/qiterator.h \
		../qt-raspi/include/QtCore/qbytearraylist.h \
		../qt-raspi/include/QtCore/qstringlist.h \
		../qt-raspi/include/QtCore/qalgorithms.h \
		../qt-raspi/include/QtCore/qstringmatcher.h \
		../qt-raspi/include/QtCore/qcoreevent.h \
		../qt-raspi/include/QtCore/qscopedpointer.h \
		../qt-raspi/include/QtCore/qmetatype.h \
		../qt-raspi/include/QtCore/qcompare.h \
		../qt-raspi/include/QtCore/qdatastream.h \
		../qt-raspi/include/QtCore/qiodevicebase.h \
		../qt-raspi/include/QtCore/qfloat16.h \
		../qt-raspi/include/QtCore/qmath.h \
		../qt-raspi/include/QtCore/qiterable.h \
		../qt-raspi/include/QtCore/qmetacontainer.h \
		../qt-raspi/include/QtCore/qcontainerinfo.h \
		../qt-raspi/include/QtCore/qtaggedpointer.h \
		../qt-raspi/include/QtCore/qscopeguard.h \
		../qt-raspi/include/QtCore/qobject_impl.h \
		../qt-raspi/include/QtCore/qbindingstorage.h \
		../qt-raspi/include/QtCore/qabstracteventdispatcher.h \
		../qt-raspi/include/QtCore/qeventloop.h \
		../qt-raspi/include/QtCore/qabstractitemmodel.h \
		../qt-raspi/include/QtCore/qhash.h \
		../qt-raspi/include/QtCore/qvariant.h \
		../qt-raspi/include/QtCore/qdebug.h \
		../qt-raspi/include/QtCore/qtextstream.h \
		../qt-raspi/include/QtCore/qstringconverter_base.h \
		../qt-raspi/include/QtCore/qcontiguouscache.h \
		../qt-raspi/include/QtCore/qsharedpointer.h \
		../qt-raspi/include/QtCore/qshareddata.h \
		../qt-raspi/include/QtCore/qsharedpointer_impl.h \
		../qt-raspi/include/QtCore/qmap.h \
		../qt-raspi/include/QtCore/qshareddata_impl.h \
		../qt-raspi/include/QtCore/qset.h \
		../qt-raspi/include/QtCore/qvarlengtharray.h \
		../qt-raspi/include/QtCore/qabstractnativeeventfilter.h \
		../qt-raspi/include/QtCore/qabstractproxymodel.h \
		../qt-raspi/include/QtCore/qanimationgroup.h \
		../qt-raspi/include/QtCore/qapplicationstatic.h \
		../qt-raspi/include/QtCore/QMutex \
		../qt-raspi/include/QtCore/qmutex.h \
		../qt-raspi/include/QtCore/qtsan_impl.h \
		../qt-raspi/include/QtCore/qcoreapplication.h \
		../qt-raspi/include/QtCore/qnativeinterface.h \
		../qt-raspi/include/QtCore/qcoreapplication_platform.h \
		../qt-raspi/include/QtCore/qfuture.h \
		../qt-raspi/include/QtCore/qfutureinterface.h \
		../qt-raspi/include/QtCore/qresultstore.h \
		../qt-raspi/include/QtCore/qfuture_impl.h \
		../qt-raspi/include/QtCore/qthreadpool.h \
		../qt-raspi/include/QtCore/qthread.h \
		../qt-raspi/include/QtCore/qdeadlinetimer.h \
		../qt-raspi/include/QtCore/qelapsedtimer.h \
		../qt-raspi/include/QtCore/qrunnable.h \
		../qt-raspi/include/QtCore/qexception.h \
		../qt-raspi/include/QtCore/qpointer.h \
		../qt-raspi/include/QtCore/qpromise.h \
		../qt-raspi/include/QtCore/qassociativeiterable.h \
		../qt-raspi/include/QtCore/qbasictimer.h \
		../qt-raspi/include/QtCore/qbitarray.h \
		../qt-raspi/include/QtCore/qbuffer.h \
		../qt-raspi/include/QtCore/qiodevice.h \
		../qt-raspi/include/QtCore/qbytearraymatcher.h \
		../qt-raspi/include/QtCore/qcache.h \
		../qt-raspi/include/QtCore/qcalendar.h \
		../qt-raspi/include/QtCore/qlocale.h \
		../qt-raspi/include/QtCore/qcborarray.h \
		../qt-raspi/include/QtCore/qcborvalue.h \
		../qt-raspi/include/QtCore/qdatetime.h \
		../qt-raspi/include/QtCore/qcborcommon.h \
		../qt-raspi/include/QtCore/qregularexpression.h \
		../qt-raspi/include/QtCore/qurl.h \
		../qt-raspi/include/QtCore/quuid.h \
		../qt-raspi/include/QtCore/qcbormap.h \
		../qt-raspi/include/QtCore/qcborstream.h \
		../qt-raspi/include/QtCore/qcborstreamreader.h \
		../qt-raspi/include/QtCore/qcborstreamwriter.h \
		../qt-raspi/include/QtCore/qcollator.h \
		../qt-raspi/include/QtCore/qcommandlineoption.h \
		../qt-raspi/include/QtCore/qcommandlineparser.h \
		../qt-raspi/include/QtCore/qconcatenatetablesproxymodel.h \
		../qt-raspi/include/QtCore/qcryptographichash.h \
		../qt-raspi/include/QtCore/qdir.h \
		../qt-raspi/include/QtCore/qfile.h \
		../qt-raspi/include/QtCore/qfiledevice.h \
		../qt-raspi/include/QtCore/qfileinfo.h \
		../qt-raspi/include/QtCore/qdiriterator.h \
		../qt-raspi/include/QtCore/qeasingcurve.h \
		../qt-raspi/include/QtCore/qendian.h \
		../qt-raspi/include/QtCore/qfactoryinterface.h \
		../qt-raspi/include/QtCore/qfileselector.h \
		../qt-raspi/include/QtCore/QObject \
		../qt-raspi/include/QtCore/QStringList \
		../qt-raspi/include/QtCore/qfilesystemwatcher.h \
		../qt-raspi/include/QtCore/qfuturesynchronizer.h \
		../qt-raspi/include/QtCore/qfuturewatcher.h \
		../qt-raspi/include/QtCore/qidentityproxymodel.h \
		../qt-raspi/include/QtCore/qitemselectionmodel.h \
		../qt-raspi/include/QtCore/qjsonarray.h \
		../qt-raspi/include/QtCore/qjsonvalue.h \
		../qt-raspi/include/QtCore/qjsondocument.h \
		../qt-raspi/include/QtCore/qjsonobject.h \
		../qt-raspi/include/QtCore/qlatin1stringmatcher.h \
		../qt-raspi/include/QtCore/qlibrary.h \
		../qt-raspi/include/QtCore/qlibraryinfo.h \
		../qt-raspi/include/QtCore/qversionnumber.h \
		../qt-raspi/include/QtCore/qline.h \
		../qt-raspi/include/QtCore/qpoint.h \
		../qt-raspi/include/QtCore/qlockfile.h \
		../qt-raspi/include/QtCore/qloggingcategory.h \
		../qt-raspi/include/QtCore/qmargins.h \
		../qt-raspi/include/QtCore/qmessageauthenticationcode.h \
		../qt-raspi/include/QtCore/qmetaobject.h \
		../qt-raspi/include/QtCore/qmimedata.h \
		../qt-raspi/include/QtCore/qmimedatabase.h \
		../qt-raspi/include/QtCore/qmimetype.h \
		../qt-raspi/include/QtCore/qobjectcleanuphandler.h \
		../qt-raspi/include/QtCore/qoperatingsystemversion.h \
		../qt-raspi/include/QtCore/qparallelanimationgroup.h \
		../qt-raspi/include/QtCore/qpauseanimation.h \
		../qt-raspi/include/QtCore/qplugin.h \
		../qt-raspi/include/QtCore/qpluginloader.h \
		../qt-raspi/include/QtCore/qprocess.h \
		../qt-raspi/include/QtCore/qproperty.h \
		../qt-raspi/include/QtCore/qpropertyprivate.h \
		../qt-raspi/include/QtCore/qpropertyanimation.h \
		../qt-raspi/include/QtCore/qvariantanimation.h \
		../qt-raspi/include/QtCore/qqueue.h \
		../qt-raspi/include/QtCore/qrandom.h \
		../qt-raspi/include/QtCore/qreadwritelock.h \
		../qt-raspi/include/QtCore/qrect.h \
		../qt-raspi/include/QtCore/qsize.h \
		../qt-raspi/include/QtCore/qresource.h \
		../qt-raspi/include/QtCore/qsavefile.h \
		../qt-raspi/include/QtCore/qscopedvaluerollback.h \
		../qt-raspi/include/QtCore/qsemaphore.h \
		../qt-raspi/include/QtCore/qsequentialanimationgroup.h \
		../qt-raspi/include/QtCore/qsequentialiterable.h \
		../qt-raspi/include/QtCore/qsettings.h \
		../qt-raspi/include/QtCore/qsharedmemory.h \
		../qt-raspi/include/QtCore/qsignalmapper.h \
		../qt-raspi/include/QtCore/qsimd.h \
		../qt-raspi/include/QtCore/qsocketnotifier.h \
		../qt-raspi/include/QtCore/qsortfilterproxymodel.h \
		../qt-raspi/include/QtCore/qstack.h \
		../qt-raspi/include/QtCore/qstandardpaths.h \
		../qt-raspi/include/QtCore/qstorageinfo.h \
		../qt-raspi/include/QtCore/qstringconverter.h \
		../qt-raspi/include/QtCore/qstringlistmodel.h \
		../qt-raspi/include/QtCore/qsystemsemaphore.h \
		../qt-raspi/include/QtCore/qtcoreversion.h \
		../qt-raspi/include/QtCore/qtemporarydir.h \
		../qt-raspi/include/QtCore/qtemporaryfile.h \
		../qt-raspi/include/QtCore/qtextboundaryfinder.h \
		../qt-raspi/include/QtCore/qthreadstorage.h \
		../qt-raspi/include/QtCore/qtimeline.h \
		../qt-raspi/include/QtCore/qtimer.h \
		../qt-raspi/include/QtCore/qtimezone.h \
		../qt-raspi/include/QtCore/qtranslator.h \
		../qt-raspi/include/QtCore/qtransposeproxymodel.h \
		../qt-raspi/include/QtCore/qurlquery.h \
		../qt-raspi/include/QtCore/qvarianthash.h \
		../qt-raspi/include/QtCore/QHash \
		../qt-raspi/include/QtCore/QVariant \
		../qt-raspi/include/QtCore/QString \
		../qt-raspi/include/QtCore/qvariantlist.h \
		../qt-raspi/include/QtCore/QList \
		../qt-raspi/include/QtCore/qvariantmap.h \
		../qt-raspi/include/QtCore/QMap \
		../qt-raspi/include/QtCore/qvector.h \
		../qt-raspi/include/QtCore/qwaitcondition.h \
		../qt-raspi/include/QtCore/QDeadlineTimer \
		../qt-raspi/include/QtCore/qwineventnotifier.h \
		../qt-raspi/include/QtCore/qxmlstream.h \
		../qt-raspi/include/QtCore/qxpfunctional.h \
		../qt-raspi/include/QtTest/qttestglobal.h \
		../qt-raspi/include/QtTest/qttestlib-config.h \
		../qt-raspi/include/QtTest/qttestexports.h \
		../qt-raspi/include/QtTest/qabstractitemmodeltester.h \
		../qt-raspi/include/QtCore/QAbstractItemModel \
		../qt-raspi/include/QtGui/QFont \
		../qt-raspi/include/QtGui/qfont.h \
		../qt-raspi/include/QtGui/qtguiglobal.h \
		../qt-raspi/include/QtGui/qtgui-config.h \
		../qt-raspi/include/QtGui/qtguiexports.h \
		../qt-raspi/include/QtGui/qwindowdefs.h \
		../qt-raspi/include/QtGui/QColor \
		../qt-raspi/include/QtGui/qcolor.h \
		../qt-raspi/include/QtGui/qrgb.h \
		../qt-raspi/include/QtGui/qrgba64.h \
		../qt-raspi/include/QtGui/QBrush \
		../qt-raspi/include/QtGui/qbrush.h \
		../qt-raspi/include/QtGui/qimage.h \
		../qt-raspi/include/QtGui/qpaintdevice.h \
		../qt-raspi/include/QtGui/qpixelformat.h \
		../qt-raspi/include/QtGui/qtransform.h \
		../qt-raspi/include/QtGui/qpolygon.h \
		../qt-raspi/include/QtGui/qregion.h \
		../qt-raspi/include/QtGui/qpixmap.h \
		../qt-raspi/include/QtGui/QPixmap \
		../qt-raspi/include/QtGui/QImage \
		../qt-raspi/include/QtGui/QIcon \
		../qt-raspi/include/QtGui/qicon.h \
		../qt-raspi/include/QtTest/qbenchmark.h \
		../qt-raspi/include/QtTest/qbenchmarkmetric.h \
		../qt-raspi/include/QtTest/qsignalspy.h \
		../qt-raspi/include/QtTest/qtesteventloop.h \
		../qt-raspi/include/QtTest/qtestcase.h \
		../qt-raspi/include/QtTest/qtest.h \
		../qt-raspi/include/QtTest/qtestdata.h \
		../qt-raspi/include/QtTest/qtestsystem.h \
		../qt-raspi/include/QtCore/qtestsupport_core.h \
		../qt-raspi/include/QtGui/qtestsupport_gui.h \
		../qt-raspi/include/QtGui/qevent.h \
		../qt-raspi/include/QtGui/qeventpoint.h \
		../qt-raspi/include/QtGui/qvector2d.h \
		../qt-raspi/include/QtGui/qvectornd.h \
		../qt-raspi/include/QtGui/qpointingdevice.h \
		../qt-raspi/include/QtGui/qinputdevice.h \
		../qt-raspi/include/QtGui/qscreen.h \
		../qt-raspi/include/QtCore/QRect \
		../qt-raspi/include/QtCore/QSize \
		../qt-raspi/include/QtCore/QSizeF \
		../qt-raspi/include/QtGui/QTransform \
		../qt-raspi/include/QtGui/qkeysequence.h \
		../qt-raspi/include/QtWidgets/qtestsupport_widgets.h \
		../qt-raspi/include/QtWidgets/qtwidgetsglobal.h \
		../qt-raspi/include/QtWidgets/qtwidgets-config.h \
		../qt-raspi/include/QtWidgets/qtwidgetsexports.h \
		../qt-raspi/include/QtTest/qtest_network.h \
		../qt-raspi/include/QtNetwork/QHostAddress \
		../qt-raspi/include/QtNetwork/qhostaddress.h \
		../qt-raspi/include/QtNetwork/qtnetworkglobal.h \
		../qt-raspi/include/QtNetwork/qtnetwork-config.h \
		../qt-raspi/include/QtNetwork/qtnetworkexports.h \
		../qt-raspi/include/QtNetwork/qabstractsocket.h \
		../qt-raspi/include/QtNetwork/QNetworkCookie \
		../qt-raspi/include/QtNetwork/qnetworkcookie.h \
		../qt-raspi/include/QtCore/QSharedDataPointer \
		../qt-raspi/include/QtCore/QMetaType \
		../qt-raspi/include/QtNetwork/QNetworkReply \
		../qt-raspi/include/QtNetwork/qnetworkreply.h \
		../qt-raspi/include/QtCore/QIODevice \
		../qt-raspi/include/QtNetwork/QNetworkRequest \
		../qt-raspi/include/QtNetwork/qnetworkrequest.h \
		../qt-raspi/include/QtCore/QUrl \
		../qt-raspi/include/QtNetwork/QNetworkAccessManager \
		../qt-raspi/include/QtNetwork/qnetworkaccessmanager.h \
		../qt-raspi/include/QtNetwork/QSslConfiguration \
		../qt-raspi/include/QtNetwork/qsslconfiguration.h \
		../qt-raspi/include/QtNetwork/qsslsocket.h \
		../qt-raspi/include/QtNetwork/qtcpsocket.h \
		../qt-raspi/include/QtNetwork/qsslerror.h \
		../qt-raspi/include/QtNetwork/qsslcertificate.h \
		../qt-raspi/include/QtNetwork/qssl.h \
		../qt-raspi/include/QtCore/QFlags \
		../qt-raspi/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../qt-raspi/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../qt-raspi/include/QtTest/qtest_widgets.h \
		../qt-raspi/include/QtTest/qtest_gui.h \
		../qt-raspi/include/QtTest/qtestassert.h \
		../qt-raspi/include/QtTest/qtestevent.h \
		../qt-raspi/include/QtTest/qtestkeyboard.h \
		../qt-raspi/include/QtTest/qtestspontaneevent.h \
		../qt-raspi/include/QtGui/qguiapplication.h \
		../qt-raspi/include/QtGui/qinputmethod.h \
		../qt-raspi/include/QtGui/qguiapplication_platform.h \
		../qt-raspi/include/QtGui/qwindow.h \
		../qt-raspi/include/QtCore/QEvent \
		../qt-raspi/include/QtCore/QMargins \
		../qt-raspi/include/QtGui/qsurface.h \
		../qt-raspi/include/QtGui/qsurfaceformat.h \
		../qt-raspi/include/QtGui/qcursor.h \
		../qt-raspi/include/QtGui/qbitmap.h \
		../qt-raspi/include/QtWidgets/qwidget.h \
		../qt-raspi/include/QtGui/qaction.h \
		../qt-raspi/include/QtGui/qpalette.h \
		../qt-raspi/include/QtGui/qfontmetrics.h \
		../qt-raspi/include/QtGui/qfontinfo.h \
		../qt-raspi/include/QtWidgets/qsizepolicy.h \
		../qt-raspi/include/QtWidgets/qapplication.h \
		../qt-raspi/include/QtTest/qtestmouse.h \
		../qt-raspi/include/QtCore/QDebug \
		../qt-raspi/include/QtTest/qtesttouch.h \
		../qt-raspi/include/QtGui/qvector3d.h \
		../qt-raspi/include/QtGui/qvector4d.h \
		../qt-raspi/include/QtWidgets/QSizePolicy \
		../qt-raspi/include/QtCore/QMetaEnum \
		../qt-raspi/include/QtTest/qttestversion.h \
		../qt-raspi/include/QtTest/QSignalSpy \
		../qt-raspi/include/QtSerialBus/QCanBus \
		../qt-raspi/include/QtSerialBus/qcanbus.h \
		../qt-raspi/include/QtSerialBus/qtserialbusglobal.h \
		../qt-raspi/include/QtSerialBus/qtserialbus-config.h \
		../qt-raspi/include/QtSerialBus/qtserialbusexports.h \
		../qt-raspi/include/QtSerialBus/qcanbusdevice.h \
		../qt-raspi/include/QtSerialBus/qcanbusframe.h \
		../qt-raspi/include/QtSerialBus/qcanbusdeviceinfo.h \
		../testBenchLibrary/keycardsactuator.h \
		../qt-raspi/include/QtSerialPort/QSerialPort \
		../qt-raspi/include/QtSerialPort/qserialport.h \
		../qt-raspi/include/QtSerialPort/qserialportglobal.h \
		../qt-raspi/include/QtSerialPort/qtserialportexports.h \
		../qt-raspi/include/QtCore/qtmochelpers.h \
		moc_predefs.h \
		../qt-host/libexec/moc
	/home/jakob/qt-host/libexec/moc $(DEFINES) --include /home/jakob/acceptanceBenchLibrary/moc_predefs.h -I/home/jakob/qt-raspi/mkspecs/devices/linux-rasp-pi4-aarch64 -I/home/jakob/acceptanceBenchLibrary -I/home/jakob/build-testBenchLibrary-Qt_6_5_3_qt_raspi-Debug -I/home/jakob/qt-raspi/include -I/home/jakob/qt-raspi/include/QtTest -I/home/jakob/qt-raspi/include/QtSerialBus -I/home/jakob/qt-raspi/include/QtNetwork -I/home/jakob/qt-raspi/include/QtSerialPort -I/home/jakob/qt-raspi/include/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include tst_test.cpp -o tst_test.moc

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_source_clean 

####### Compile

tst_test.o: tst_test.cpp ../qt-raspi/include/QtTest/QtTest \
		../qt-raspi/include/QtTest/QtTestDepends \
		../qt-raspi/include/QtCore/QtCore \
		../qt-raspi/include/QtCore/QtCoreDepends \
		../qt-raspi/include/QtCore/qglobal.h \
		../qt-raspi/include/QtCore/qtversionchecks.h \
		../qt-raspi/include/QtCore/qconfig.h \
		../qt-raspi/include/QtCore/qtcore-config.h \
		../qt-raspi/include/QtCore/qtconfigmacros.h \
		../qt-raspi/include/QtCore/qtcoreexports.h \
		../qt-raspi/include/QtCore/qtpreprocessorsupport.h \
		../qt-raspi/include/QtCore/qtnoop.h \
		../qt-raspi/include/QtCore/qsystemdetection.h \
		../qt-raspi/include/QtCore/qprocessordetection.h \
		../qt-raspi/include/QtCore/qcompilerdetection.h \
		../qt-raspi/include/QtCore/qassert.h \
		../qt-raspi/include/QtCore/qtypes.h \
		../qt-raspi/include/QtCore/qtclasshelpermacros.h \
		../qt-raspi/include/QtCore/qtversion.h \
		../qt-raspi/include/QtCore/qtypeinfo.h \
		../qt-raspi/include/QtCore/qcontainerfwd.h \
		../qt-raspi/include/QtCore/qsysinfo.h \
		../qt-raspi/include/QtCore/qlogging.h \
		../qt-raspi/include/QtCore/qflags.h \
		../qt-raspi/include/QtCore/qcompare_impl.h \
		../qt-raspi/include/QtCore/qatomic.h \
		../qt-raspi/include/QtCore/qbasicatomic.h \
		../qt-raspi/include/QtCore/qatomic_cxx11.h \
		../qt-raspi/include/QtCore/qgenericatomic.h \
		../qt-raspi/include/QtCore/qconstructormacros.h \
		../qt-raspi/include/QtCore/qdarwinhelpers.h \
		../qt-raspi/include/QtCore/qexceptionhandling.h \
		../qt-raspi/include/QtCore/qforeach.h \
		../qt-raspi/include/QtCore/qtdeprecationmarkers.h \
		../qt-raspi/include/QtCore/qttypetraits.h \
		../qt-raspi/include/QtCore/qfunctionpointer.h \
		../qt-raspi/include/QtCore/qglobalstatic.h \
		../qt-raspi/include/QtCore/qmalloc.h \
		../qt-raspi/include/QtCore/qminmax.h \
		../qt-raspi/include/QtCore/qnumeric.h \
		../qt-raspi/include/QtCore/qoverload.h \
		../qt-raspi/include/QtCore/qswap.h \
		../qt-raspi/include/QtCore/qtenvironmentvariables.h \
		../qt-raspi/include/QtCore/qtresource.h \
		../qt-raspi/include/QtCore/qttranslation.h \
		../qt-raspi/include/QtCore/qversiontagging.h \
		../qt-raspi/include/QtCore/q20algorithm.h \
		../qt-raspi/include/QtCore/q20functional.h \
		../qt-raspi/include/QtCore/q20iterator.h \
		../qt-raspi/include/QtCore/q20memory.h \
		../qt-raspi/include/QtCore/q23functional.h \
		../qt-raspi/include/QtCore/qabstractanimation.h \
		../qt-raspi/include/QtCore/qobject.h \
		../qt-raspi/include/QtCore/qobjectdefs.h \
		../qt-raspi/include/QtCore/qnamespace.h \
		../qt-raspi/include/QtCore/qtmetamacros.h \
		../qt-raspi/include/QtCore/qobjectdefs_impl.h \
		../qt-raspi/include/QtCore/qstring.h \
		../qt-raspi/include/QtCore/qchar.h \
		../qt-raspi/include/QtCore/qstringview.h \
		../qt-raspi/include/QtCore/qbytearray.h \
		../qt-raspi/include/QtCore/qrefcount.h \
		../qt-raspi/include/QtCore/qarraydata.h \
		../qt-raspi/include/QtCore/qpair.h \
		../qt-raspi/include/QtCore/qarraydatapointer.h \
		../qt-raspi/include/QtCore/qarraydataops.h \
		../qt-raspi/include/QtCore/qcontainertools_impl.h \
		../qt-raspi/include/QtCore/qxptype_traits.h \
		../qt-raspi/include/QtCore/qbytearrayalgorithms.h \
		../qt-raspi/include/QtCore/qbytearrayview.h \
		../qt-raspi/include/QtCore/qstringfwd.h \
		../qt-raspi/include/QtCore/q20type_traits.h \
		../qt-raspi/include/QtCore/qstringliteral.h \
		../qt-raspi/include/QtCore/qstringalgorithms.h \
		../qt-raspi/include/QtCore/qanystringview.h \
		../qt-raspi/include/QtCore/qutf8stringview.h \
		../qt-raspi/include/QtCore/qstringtokenizer.h \
		../qt-raspi/include/QtCore/qstringbuilder.h \
		../qt-raspi/include/QtCore/qlist.h \
		../qt-raspi/include/QtCore/qhashfunctions.h \
		../qt-raspi/include/QtCore/qiterator.h \
		../qt-raspi/include/QtCore/qbytearraylist.h \
		../qt-raspi/include/QtCore/qstringlist.h \
		../qt-raspi/include/QtCore/qalgorithms.h \
		../qt-raspi/include/QtCore/qstringmatcher.h \
		../qt-raspi/include/QtCore/qcoreevent.h \
		../qt-raspi/include/QtCore/qscopedpointer.h \
		../qt-raspi/include/QtCore/qmetatype.h \
		../qt-raspi/include/QtCore/qcompare.h \
		../qt-raspi/include/QtCore/qdatastream.h \
		../qt-raspi/include/QtCore/qiodevicebase.h \
		../qt-raspi/include/QtCore/qfloat16.h \
		../qt-raspi/include/QtCore/qmath.h \
		../qt-raspi/include/QtCore/qiterable.h \
		../qt-raspi/include/QtCore/qmetacontainer.h \
		../qt-raspi/include/QtCore/qcontainerinfo.h \
		../qt-raspi/include/QtCore/qtaggedpointer.h \
		../qt-raspi/include/QtCore/qscopeguard.h \
		../qt-raspi/include/QtCore/qobject_impl.h \
		../qt-raspi/include/QtCore/qbindingstorage.h \
		../qt-raspi/include/QtCore/qabstracteventdispatcher.h \
		../qt-raspi/include/QtCore/qeventloop.h \
		../qt-raspi/include/QtCore/qabstractitemmodel.h \
		../qt-raspi/include/QtCore/qhash.h \
		../qt-raspi/include/QtCore/qvariant.h \
		../qt-raspi/include/QtCore/qdebug.h \
		../qt-raspi/include/QtCore/qtextstream.h \
		../qt-raspi/include/QtCore/qstringconverter_base.h \
		../qt-raspi/include/QtCore/qcontiguouscache.h \
		../qt-raspi/include/QtCore/qsharedpointer.h \
		../qt-raspi/include/QtCore/qshareddata.h \
		../qt-raspi/include/QtCore/qsharedpointer_impl.h \
		../qt-raspi/include/QtCore/qmap.h \
		../qt-raspi/include/QtCore/qshareddata_impl.h \
		../qt-raspi/include/QtCore/qset.h \
		../qt-raspi/include/QtCore/qvarlengtharray.h \
		../qt-raspi/include/QtCore/qabstractnativeeventfilter.h \
		../qt-raspi/include/QtCore/qabstractproxymodel.h \
		../qt-raspi/include/QtCore/qanimationgroup.h \
		../qt-raspi/include/QtCore/qapplicationstatic.h \
		../qt-raspi/include/QtCore/QMutex \
		../qt-raspi/include/QtCore/qmutex.h \
		../qt-raspi/include/QtCore/qtsan_impl.h \
		../qt-raspi/include/QtCore/qcoreapplication.h \
		../qt-raspi/include/QtCore/qnativeinterface.h \
		../qt-raspi/include/QtCore/qcoreapplication_platform.h \
		../qt-raspi/include/QtCore/qfuture.h \
		../qt-raspi/include/QtCore/qfutureinterface.h \
		../qt-raspi/include/QtCore/qresultstore.h \
		../qt-raspi/include/QtCore/qfuture_impl.h \
		../qt-raspi/include/QtCore/qthreadpool.h \
		../qt-raspi/include/QtCore/qthread.h \
		../qt-raspi/include/QtCore/qdeadlinetimer.h \
		../qt-raspi/include/QtCore/qelapsedtimer.h \
		../qt-raspi/include/QtCore/qrunnable.h \
		../qt-raspi/include/QtCore/qexception.h \
		../qt-raspi/include/QtCore/qpointer.h \
		../qt-raspi/include/QtCore/qpromise.h \
		../qt-raspi/include/QtCore/qassociativeiterable.h \
		../qt-raspi/include/QtCore/qbasictimer.h \
		../qt-raspi/include/QtCore/qbitarray.h \
		../qt-raspi/include/QtCore/qbuffer.h \
		../qt-raspi/include/QtCore/qiodevice.h \
		../qt-raspi/include/QtCore/qbytearraymatcher.h \
		../qt-raspi/include/QtCore/qcache.h \
		../qt-raspi/include/QtCore/qcalendar.h \
		../qt-raspi/include/QtCore/qlocale.h \
		../qt-raspi/include/QtCore/qcborarray.h \
		../qt-raspi/include/QtCore/qcborvalue.h \
		../qt-raspi/include/QtCore/qdatetime.h \
		../qt-raspi/include/QtCore/qcborcommon.h \
		../qt-raspi/include/QtCore/qregularexpression.h \
		../qt-raspi/include/QtCore/qurl.h \
		../qt-raspi/include/QtCore/quuid.h \
		../qt-raspi/include/QtCore/qcbormap.h \
		../qt-raspi/include/QtCore/qcborstream.h \
		../qt-raspi/include/QtCore/qcborstreamreader.h \
		../qt-raspi/include/QtCore/qcborstreamwriter.h \
		../qt-raspi/include/QtCore/qcollator.h \
		../qt-raspi/include/QtCore/qcommandlineoption.h \
		../qt-raspi/include/QtCore/qcommandlineparser.h \
		../qt-raspi/include/QtCore/qconcatenatetablesproxymodel.h \
		../qt-raspi/include/QtCore/qcryptographichash.h \
		../qt-raspi/include/QtCore/qdir.h \
		../qt-raspi/include/QtCore/qfile.h \
		../qt-raspi/include/QtCore/qfiledevice.h \
		../qt-raspi/include/QtCore/qfileinfo.h \
		../qt-raspi/include/QtCore/qdiriterator.h \
		../qt-raspi/include/QtCore/qeasingcurve.h \
		../qt-raspi/include/QtCore/qendian.h \
		../qt-raspi/include/QtCore/qfactoryinterface.h \
		../qt-raspi/include/QtCore/qfileselector.h \
		../qt-raspi/include/QtCore/QObject \
		../qt-raspi/include/QtCore/QStringList \
		../qt-raspi/include/QtCore/qfilesystemwatcher.h \
		../qt-raspi/include/QtCore/qfuturesynchronizer.h \
		../qt-raspi/include/QtCore/qfuturewatcher.h \
		../qt-raspi/include/QtCore/qidentityproxymodel.h \
		../qt-raspi/include/QtCore/qitemselectionmodel.h \
		../qt-raspi/include/QtCore/qjsonarray.h \
		../qt-raspi/include/QtCore/qjsonvalue.h \
		../qt-raspi/include/QtCore/qjsondocument.h \
		../qt-raspi/include/QtCore/qjsonobject.h \
		../qt-raspi/include/QtCore/qlatin1stringmatcher.h \
		../qt-raspi/include/QtCore/qlibrary.h \
		../qt-raspi/include/QtCore/qlibraryinfo.h \
		../qt-raspi/include/QtCore/qversionnumber.h \
		../qt-raspi/include/QtCore/qline.h \
		../qt-raspi/include/QtCore/qpoint.h \
		../qt-raspi/include/QtCore/qlockfile.h \
		../qt-raspi/include/QtCore/qloggingcategory.h \
		../qt-raspi/include/QtCore/qmargins.h \
		../qt-raspi/include/QtCore/qmessageauthenticationcode.h \
		../qt-raspi/include/QtCore/qmetaobject.h \
		../qt-raspi/include/QtCore/qmimedata.h \
		../qt-raspi/include/QtCore/qmimedatabase.h \
		../qt-raspi/include/QtCore/qmimetype.h \
		../qt-raspi/include/QtCore/qobjectcleanuphandler.h \
		../qt-raspi/include/QtCore/qoperatingsystemversion.h \
		../qt-raspi/include/QtCore/qparallelanimationgroup.h \
		../qt-raspi/include/QtCore/qpauseanimation.h \
		../qt-raspi/include/QtCore/qplugin.h \
		../qt-raspi/include/QtCore/qpluginloader.h \
		../qt-raspi/include/QtCore/qprocess.h \
		../qt-raspi/include/QtCore/qproperty.h \
		../qt-raspi/include/QtCore/qpropertyprivate.h \
		../qt-raspi/include/QtCore/qpropertyanimation.h \
		../qt-raspi/include/QtCore/qvariantanimation.h \
		../qt-raspi/include/QtCore/qqueue.h \
		../qt-raspi/include/QtCore/qrandom.h \
		../qt-raspi/include/QtCore/qreadwritelock.h \
		../qt-raspi/include/QtCore/qrect.h \
		../qt-raspi/include/QtCore/qsize.h \
		../qt-raspi/include/QtCore/qresource.h \
		../qt-raspi/include/QtCore/qsavefile.h \
		../qt-raspi/include/QtCore/qscopedvaluerollback.h \
		../qt-raspi/include/QtCore/qsemaphore.h \
		../qt-raspi/include/QtCore/qsequentialanimationgroup.h \
		../qt-raspi/include/QtCore/qsequentialiterable.h \
		../qt-raspi/include/QtCore/qsettings.h \
		../qt-raspi/include/QtCore/qsharedmemory.h \
		../qt-raspi/include/QtCore/qsignalmapper.h \
		../qt-raspi/include/QtCore/qsimd.h \
		../qt-raspi/include/QtCore/qsocketnotifier.h \
		../qt-raspi/include/QtCore/qsortfilterproxymodel.h \
		../qt-raspi/include/QtCore/qstack.h \
		../qt-raspi/include/QtCore/qstandardpaths.h \
		../qt-raspi/include/QtCore/qstorageinfo.h \
		../qt-raspi/include/QtCore/qstringconverter.h \
		../qt-raspi/include/QtCore/qstringlistmodel.h \
		../qt-raspi/include/QtCore/qsystemsemaphore.h \
		../qt-raspi/include/QtCore/qtcoreversion.h \
		../qt-raspi/include/QtCore/qtemporarydir.h \
		../qt-raspi/include/QtCore/qtemporaryfile.h \
		../qt-raspi/include/QtCore/qtextboundaryfinder.h \
		../qt-raspi/include/QtCore/qthreadstorage.h \
		../qt-raspi/include/QtCore/qtimeline.h \
		../qt-raspi/include/QtCore/qtimer.h \
		../qt-raspi/include/QtCore/qtimezone.h \
		../qt-raspi/include/QtCore/qtranslator.h \
		../qt-raspi/include/QtCore/qtransposeproxymodel.h \
		../qt-raspi/include/QtCore/qurlquery.h \
		../qt-raspi/include/QtCore/qvarianthash.h \
		../qt-raspi/include/QtCore/QHash \
		../qt-raspi/include/QtCore/QVariant \
		../qt-raspi/include/QtCore/QString \
		../qt-raspi/include/QtCore/qvariantlist.h \
		../qt-raspi/include/QtCore/QList \
		../qt-raspi/include/QtCore/qvariantmap.h \
		../qt-raspi/include/QtCore/QMap \
		../qt-raspi/include/QtCore/qvector.h \
		../qt-raspi/include/QtCore/qwaitcondition.h \
		../qt-raspi/include/QtCore/QDeadlineTimer \
		../qt-raspi/include/QtCore/qwineventnotifier.h \
		../qt-raspi/include/QtCore/qxmlstream.h \
		../qt-raspi/include/QtCore/qxpfunctional.h \
		../qt-raspi/include/QtTest/qttestglobal.h \
		../qt-raspi/include/QtTest/qttestlib-config.h \
		../qt-raspi/include/QtTest/qttestexports.h \
		../qt-raspi/include/QtTest/qabstractitemmodeltester.h \
		../qt-raspi/include/QtCore/QAbstractItemModel \
		../qt-raspi/include/QtGui/QFont \
		../qt-raspi/include/QtGui/qfont.h \
		../qt-raspi/include/QtGui/qtguiglobal.h \
		../qt-raspi/include/QtGui/qtgui-config.h \
		../qt-raspi/include/QtGui/qtguiexports.h \
		../qt-raspi/include/QtGui/qwindowdefs.h \
		../qt-raspi/include/QtGui/QColor \
		../qt-raspi/include/QtGui/qcolor.h \
		../qt-raspi/include/QtGui/qrgb.h \
		../qt-raspi/include/QtGui/qrgba64.h \
		../qt-raspi/include/QtGui/QBrush \
		../qt-raspi/include/QtGui/qbrush.h \
		../qt-raspi/include/QtGui/qimage.h \
		../qt-raspi/include/QtGui/qpaintdevice.h \
		../qt-raspi/include/QtGui/qpixelformat.h \
		../qt-raspi/include/QtGui/qtransform.h \
		../qt-raspi/include/QtGui/qpolygon.h \
		../qt-raspi/include/QtGui/qregion.h \
		../qt-raspi/include/QtGui/qpixmap.h \
		../qt-raspi/include/QtGui/QPixmap \
		../qt-raspi/include/QtGui/QImage \
		../qt-raspi/include/QtGui/QIcon \
		../qt-raspi/include/QtGui/qicon.h \
		../qt-raspi/include/QtTest/qbenchmark.h \
		../qt-raspi/include/QtTest/qbenchmarkmetric.h \
		../qt-raspi/include/QtTest/qsignalspy.h \
		../qt-raspi/include/QtTest/qtesteventloop.h \
		../qt-raspi/include/QtTest/qtestcase.h \
		../qt-raspi/include/QtTest/qtest.h \
		../qt-raspi/include/QtTest/qtestdata.h \
		../qt-raspi/include/QtTest/qtestsystem.h \
		../qt-raspi/include/QtCore/qtestsupport_core.h \
		../qt-raspi/include/QtGui/qtestsupport_gui.h \
		../qt-raspi/include/QtGui/qevent.h \
		../qt-raspi/include/QtGui/qeventpoint.h \
		../qt-raspi/include/QtGui/qvector2d.h \
		../qt-raspi/include/QtGui/qvectornd.h \
		../qt-raspi/include/QtGui/qpointingdevice.h \
		../qt-raspi/include/QtGui/qinputdevice.h \
		../qt-raspi/include/QtGui/qscreen.h \
		../qt-raspi/include/QtCore/QRect \
		../qt-raspi/include/QtCore/QSize \
		../qt-raspi/include/QtCore/QSizeF \
		../qt-raspi/include/QtGui/QTransform \
		../qt-raspi/include/QtGui/qkeysequence.h \
		../qt-raspi/include/QtWidgets/qtestsupport_widgets.h \
		../qt-raspi/include/QtWidgets/qtwidgetsglobal.h \
		../qt-raspi/include/QtWidgets/qtwidgets-config.h \
		../qt-raspi/include/QtWidgets/qtwidgetsexports.h \
		../qt-raspi/include/QtTest/qtest_network.h \
		../qt-raspi/include/QtNetwork/QHostAddress \
		../qt-raspi/include/QtNetwork/qhostaddress.h \
		../qt-raspi/include/QtNetwork/qtnetworkglobal.h \
		../qt-raspi/include/QtNetwork/qtnetwork-config.h \
		../qt-raspi/include/QtNetwork/qtnetworkexports.h \
		../qt-raspi/include/QtNetwork/qabstractsocket.h \
		../qt-raspi/include/QtNetwork/QNetworkCookie \
		../qt-raspi/include/QtNetwork/qnetworkcookie.h \
		../qt-raspi/include/QtCore/QSharedDataPointer \
		../qt-raspi/include/QtCore/QMetaType \
		../qt-raspi/include/QtNetwork/QNetworkReply \
		../qt-raspi/include/QtNetwork/qnetworkreply.h \
		../qt-raspi/include/QtCore/QIODevice \
		../qt-raspi/include/QtNetwork/QNetworkRequest \
		../qt-raspi/include/QtNetwork/qnetworkrequest.h \
		../qt-raspi/include/QtCore/QUrl \
		../qt-raspi/include/QtNetwork/QNetworkAccessManager \
		../qt-raspi/include/QtNetwork/qnetworkaccessmanager.h \
		../qt-raspi/include/QtNetwork/QSslConfiguration \
		../qt-raspi/include/QtNetwork/qsslconfiguration.h \
		../qt-raspi/include/QtNetwork/qsslsocket.h \
		../qt-raspi/include/QtNetwork/qtcpsocket.h \
		../qt-raspi/include/QtNetwork/qsslerror.h \
		../qt-raspi/include/QtNetwork/qsslcertificate.h \
		../qt-raspi/include/QtNetwork/qssl.h \
		../qt-raspi/include/QtCore/QFlags \
		../qt-raspi/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../qt-raspi/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../qt-raspi/include/QtTest/qtest_widgets.h \
		../qt-raspi/include/QtTest/qtest_gui.h \
		../qt-raspi/include/QtTest/qtestassert.h \
		../qt-raspi/include/QtTest/qtestevent.h \
		../qt-raspi/include/QtTest/qtestkeyboard.h \
		../qt-raspi/include/QtTest/qtestspontaneevent.h \
		../qt-raspi/include/QtGui/qguiapplication.h \
		../qt-raspi/include/QtGui/qinputmethod.h \
		../qt-raspi/include/QtGui/qguiapplication_platform.h \
		../qt-raspi/include/QtGui/qwindow.h \
		../qt-raspi/include/QtCore/QEvent \
		../qt-raspi/include/QtCore/QMargins \
		../qt-raspi/include/QtGui/qsurface.h \
		../qt-raspi/include/QtGui/qsurfaceformat.h \
		../qt-raspi/include/QtGui/qcursor.h \
		../qt-raspi/include/QtGui/qbitmap.h \
		../qt-raspi/include/QtWidgets/qwidget.h \
		../qt-raspi/include/QtGui/qaction.h \
		../qt-raspi/include/QtGui/qpalette.h \
		../qt-raspi/include/QtGui/qfontmetrics.h \
		../qt-raspi/include/QtGui/qfontinfo.h \
		../qt-raspi/include/QtWidgets/qsizepolicy.h \
		../qt-raspi/include/QtWidgets/qapplication.h \
		../qt-raspi/include/QtTest/qtestmouse.h \
		../qt-raspi/include/QtCore/QDebug \
		../qt-raspi/include/QtTest/qtesttouch.h \
		../qt-raspi/include/QtGui/qvector3d.h \
		../qt-raspi/include/QtGui/qvector4d.h \
		../qt-raspi/include/QtWidgets/QSizePolicy \
		../qt-raspi/include/QtCore/QMetaEnum \
		../qt-raspi/include/QtTest/qttestversion.h \
		../qt-raspi/include/QtTest/QSignalSpy \
		../qt-raspi/include/QtSerialBus/QCanBus \
		../qt-raspi/include/QtSerialBus/qcanbus.h \
		../qt-raspi/include/QtSerialBus/qtserialbusglobal.h \
		../qt-raspi/include/QtSerialBus/qtserialbus-config.h \
		../qt-raspi/include/QtSerialBus/qtserialbusexports.h \
		../qt-raspi/include/QtSerialBus/qcanbusdevice.h \
		../qt-raspi/include/QtSerialBus/qcanbusframe.h \
		../qt-raspi/include/QtSerialBus/qcanbusdeviceinfo.h \
		../testBenchLibrary/keycardsactuator.h \
		../qt-raspi/include/QtSerialPort/QSerialPort \
		../qt-raspi/include/QtSerialPort/qserialport.h \
		../qt-raspi/include/QtSerialPort/qserialportglobal.h \
		../qt-raspi/include/QtSerialPort/qtserialportexports.h \
		tst_test.moc \
		../qt-raspi/include/QtCore/qtmochelpers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tst_test.o tst_test.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/jakob/qt-raspi/tests/acceptanceBenchLibrary || mkdir -p $(INSTALL_ROOT)/home/jakob/qt-raspi/tests/acceptanceBenchLibrary
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/home/jakob/qt-raspi/tests/acceptanceBenchLibrary/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/home/jakob/qt-raspi/tests/acceptanceBenchLibrary/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/home/jakob/qt-raspi/tests/acceptanceBenchLibrary/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

